In [ ]:
http://opendata.minneapolismn.gov/
https://brigades.opendatanetwork.com/brigade?brigade=Open%20Twin%20Cities
https://collections.artsmia.org

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv("Public_311_2017.csv")

In [3]:
df.head()

,X,Y,CASEID,OBJECTID,SUBJECTNAME,REASONNAME,TYPENAME,TITLE,OPENEDDATETIME,CASESTATUS,CLOSEDDATETIME,XCOORD,YCOORD,LastUpdateDate
0,-93.301374,45.048907,-2075223591,14001,Vehicles and Commuting,Traffic Control,Abandoned Vehicle,NaN,2017-02-05T10:36:16.000Z,0,2017-02-08T16:46:50.000Z,-1.038626e+07,5.629224e+06,2017-06-14T14:08:29.000Z
1,-93.214364,44.948638,-2075223588,14002,Vehicles and Commuting,Traffic Control,Parking Violation Complaint,NaN,2017-02-05T10:58:22.000Z,0,2017-02-05T11:36:26.000Z,-1.037658e+07,5.613439e+06,2017-06-14T15:03:52.000Z
2,-93.262410,44.996134,-2075223576,14003,Animal Related,Animal Control,Animal Complaint - Livability,Animal Complaint - Livability,2017-02-05T11:56:55.000Z,0,2017-02-06T12:12:09.000Z,-1.038192e+07,5.620913e+06,2017-02-07T21:00:42.000Z
3,-93.228880,44.901878,-2075223574,14004,Animal Related,Animal Control,Animal Complaint - Livability,Animal Complaint - Livability,2017-02-05T12:17:27.000Z,0,2017-02-06T16:29:49.000Z,-1.037819e+07,5.606087e+06,2017-02-07T21:00:42.000Z
4,-93.300976,44.978689,-2075223559,14005,Animal Related,Animal Control,Animal Complaint - Public Health,Animal Complaint - Public Health,2017-02-05T13:56:56.000Z,0,2017-02-05T14:42:27.000Z,-1.038622e+07,5.618167e+06,2017-02-07T21:00:42.000Z